# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20180115_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='blocking_jobs',
            field=models.ManyToManyField(to='logger.job'),
        ),
    ]
