# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-08 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20180118_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='maintainers',
            field=models.ManyToManyField(related_name='_schedule_maintainers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
